name: Testing on ubuntu-latest

on: [push, pull_request]

env:
  SKBUILD_BUILD_OPTIONS: --verbose

jobs:
  build-depends:
    uses: ./.github/workflows/test-linux-dependencies.yml

  build:
    needs: build-depends
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up requirements & configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade pip wheel
          echo "SKBUILD_BUILD_OPTIONS=${{ env.SKBUILD_BUILD_OPTIONS }}" >> "$GITHUB_ENV"

      ### libcasm-global ###
      - name: restore libcasm-global cache
        id: cache-libcasm-global-restore
        uses: actions/cache/restore@v4
        with:
          path: CASMcode_global/dist
          key: ${{ runner.os }}-libcasm-global-v2-0-3

      ### libcasm-xtal ###
      - name: restore libcasm-xtal cache
        id: cache-libcasm-xtal-restore
        uses: actions/cache/restore@v4
        with:
          path: CASMcode_crystallography/dist
          key: ${{ runner.os }}-libcasm-xtal-v2-0a8

      - name: Install CASM dependencies
        run: |
          pip install CASMcode_global/dist/*.whl
          pip install CASMcode_crystallography/dist/*.whl
          pip install -r build_requirements.txt

      - name: make
        shell: bash
        run: |
          pip install -v .

      - name: make test
        shell: bash
        run: |
          pip install -r test_requirements.txt
          python -m pytest -rsap python/tests

      - name: Set up doc requirements
        run: |
          pip install -r doc_requirements.txt

      - name: build docs
        shell: bash
        run: |
          cd python/doc
          sphinx-build -b html . _build/html

      - name: upload docs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: libcasm-mapping-docs
          path: python/doc/_build/html
